Error: HTTP Status 403 for request POST https://api.github.com/repos/ilysokon/meteo/dependency-graph/snapshots Error: Response body: {   "message": "Resource not accessible by integration",   "documentation_url": "https://docs.github.com/rest/dependency-graph/dependency-submission#create-a-snapshot-of-dependencies-for-a-repository",   "status": "403" }

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -33,6 +33,15 @@ jobs:
         java-version: '17'
         distribution: 'temurin'
         cache: maven
+
+    - name: Cache Maven packages
+      uses: actions/cache@v2
+      with:
+        path: ~/.m2/repository
+        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+        restore-keys: |
+          ${{ runner.os }}-maven-
+
     - name: Build with Maven
       run: mvn -B package --file pom.xml
 
@@ -42,11 +51,16 @@ jobs:
 
     - name: Submit dependency snapshot
       run: |
-        curl -X POST \
-        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-        -H "Content-Type: application/json" \
-        -d @dependencies.json \
-        https://api.github.com/repos/${{ github.repository }}/dependency-graph/snapshots   
+          if [ -f dependencies.json ]; then
+            curl -X POST \
+            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            -H "Content-Type: application/json" \
+            -d @dependencies.json \
+            https://api.github.com/repos/${{ github.repository }}/dependency-graph/snapshots
+          else
+            echo "dependencies.json file not found."
+            exit 1
+          fi   
 
     # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
     - name: Update dependency graph
